application:
  subdomain: hoodik
  background_task: true
  multi_instance: false
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://hoodik:5443/
services:
  hoodik:
    # upstream: hudik/hoodik:v2.5.2
    image: registry.lazycat.cloud/czyt/hudik/hoodik:4f12300cc22c3846
    environment:
      - APP_URL=https://${LAZYCAT_APP_DOMAIN}
      - DATA_DIR=/data
      - SSL_DISABLED=true
    binds:
      - /lzcapp/var/data:/data
    setup_script: |
      if ! [ -f /data/env.yml ];then
        cp -f /lzcapp/pkg/content/env.yml /data/env.yml
      fi
      source /data/env.yml
