lzc-sdk-version: "0.1"
name: hoodik
package: cloud.lazycat.app.hoodik
version: 1.5.1
description: 轻量级、安全且易于自建的云存储解决方案
homepage: https://github.com/hudikhq/hoodik
author: hudikhq
application:
  subdomain: hoodik
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  routes:
    - /=http://hoodik:5443/
services:
  hoodik:
    image: docker.hlmirror.com/hudik/hoodik:v1.5.1
    environment:
      - APP_URL=https://${LAZYCAT_APP_DOMAIN}
      - DATA_DIR=/data
      - SSL_DISABLED=true
    binds:
      - /lzcapp/var/data:/data
    setup_script: |
      if ! [ -f /data/env.yml ];then
        cp -f /lzcapp/pkg/content/env.yml /data/env.yml
      fi
      source /data/env.yml
